### ISSUE TITLE
Developer - API - I should be able to CRUD Exercises

### ISSUE THREAD

**Issue by peterbsmyth** [bod-project/bod-api#1]
#### Scenario

Given: 
When: 
Then: 

#### Acceptance Criteria
-

**Comment by tmonks** [comment]
- Researched Loopback & did a successful local test with the Exercise model & functioning endpoints
- Researched PostgreSQL connector. Did a successful local test to generate models from Loopback into local db schema and was able to populate and query records through Loopback API endpoints

**Comment by tmonks** [comment]
- completed a successful test of running Loopback locally and using PostgreSQL database on Heroku
- working through errors deploying Loopback to Heroku on my personal testing account

**Comment by tmonks** [comment]
Successfully deployed Loopback to Heroku & Postgres with the Exercise model! 

Please give it a try:  http://bod-api-2.herokuapp.com/exercises

**Comment by peterbsmyth** [comment]
14:14
