### ISSUE TITLE
API V2

### ISSUE THREAD

**Issue by peterbsmyth** [bod-project/bod-api#11]
# Interfaces V2
## User
```ts
export interface User {
  id: number;
  name: string;
  realm: string;
  username: string;
  verificationToken: string;
  emailVerified: boolean;
  role?: string; // 'coach' or 'athlete'
  instagramUsername?: string;
}

```

## Nutrition
```ts
interface Food {
  id: number;
  name: string; // chicken
  categories: Category[]; // fat, protein, carbohydrate, vegetable
  quantity: string[]; // 200g or 300g or 1.5 cups
  createdBy: User;
}
```

```ts
interface Meal {
  id: number;
  program: Program;
  food: Food;
  week: number;
  day: number;
  order: number;
  chosenFood: Food;
}
```

```ts
interface MealPlan {
  id: number;
  name: number;
  meals: Meal[];
  createdBy: User;
  assignedTo: User;
}
```

## Training
```ts
interface Exercise {
  id?: number;
  name: string; // tuck planche hold
  categories: Category[];
  intensities: Intensity[];
  leftRight: boolean;
  measuredBy: string; // either 'secs' or 'reps' as the unit for measuring duration or quantity measurement
  demonstrationVideos: DemonstrationVideo[];
  createdBy: User;
}
```

```ts
export interface Intensity {
  id: number;
  exerciseId?: number;
  exercise?: Exercise;
  order: number;
  name: string;
  createdBy: User;
}
```

```ts
interface DemonstrationVideo {
  id: number;
  type: string; // instagram or youtube
  url: string;
}
```

```ts
export interface Program {
  id?: number;
  number: number;
  workouts?: Workout[];
  setStatistics?: SetStatistic[];
  playlist?: Playlist;
  createdBy?: User;
  assignedTo?: User;
}
```

```ts
export interface Workout {
  id: number;
  programId: number;
  program?: Program;
  exerciseId: number;
  exercise?: Exercise;
  week: number;
  day: number;
  order: number;
  reps: number; // 8
  amrap: boolean; // true
  setCount: number; // 3
  sets?: Set[];
  weight: number; // 10
  weightUnit: string; // 'lbs' or 'kg'
  intensityId: number;
  intensity?: Intensity;
  tempo: string; // '5s eccentric, 2s hold at bottom'
  notes: string; // 'squeeze at top'
  playlistUrl?: string;
  rpe?: number; // 8
  athleteNotes?: string; // 'not at my full strength'
  setStatistics: SetStatistic[];
}
```

```ts
export interface Set {
  id: number;
  order: number;
  notes: string;
  weight: number;
  reps: number;
}
```

```ts
export interface SetStatistic {
  id: number;
  set: number; // 1
  reps: number; // 8
  weight?: number; // 35
  workoutId?: number;
  workout?: Workout;
  programId?: number;
  program?: Program;
}
```

```ts
export interface Playlist {
  id: number;
  url: string;
  week?: number;
  programId?: number;
  program?: Program;
}

```

## Shared
```ts
export interface Category {
  id: number;
  name: string;
  createdBy: User;
}
```

**Comment by peterbsmyth** [comment]
Primary enhancements:
- Simplification of the model hierarchy from:
  - previous: Program => Week => Session => SessionItem
  - proposed: Program => SessionItem

- Display for durational exercises
  - isometric holds are measured in seconds, not reps, API can reflect that

- Including createdAt and updatedAt properties
  - having timestamps enabled will allow tracking of time-based statistics

- Demonstration Video
  - allow coaches to save demonstration videos

- Handstand Model
  - a skill-based exercise has a different model and tracking than strength-based exercises. so it gets its own model

Other Changes:
- `AMRAP` => `amrap`
  - its an acronym, so it was capitalized. Its no a constant, so we switch to the programming convention of using only all caps for constants. 
- remove `leftRight` from `SessionItem`, it can be got from `Exercise`.
- include `playlist` in `WeekStatistic`

**Comment by tmonks** [comment]
Couple questions for you on the new models @peterbsmith2 :

- Can you please add the `MealStatistic` model?
- Can 'V2' be removed from the model names, since we're going to create a new app for V2?
- One-to-One relationships are defined as "Source hasOne Target". The Source gets an "inclusion resolver" so that the Target can be included in request for the Source by specifying the relation name in the request body (i.e. `{ "include": [ { "relation": "target" } ] }`). Target gets a foreign key like `sourceId`. Can you please confirm these two one-to-one relationships should be set up as shown below?
	- Meal (Source) hasOne MealStatistic (Target)
	- Program (Source) hasOne Playlist (Target)

**Comment by peterbsmyth** [comment]
- removed the `MealStatistic` references. It's no longer a part of the API
- V2 is removed from names
- meal no longer has a meal stat relationship.
- yes program is the source and playlist is the target.
