### ISSUE TITLE
Developer - API - I should be able to CRUD SessionItems

### ISSUE THREAD

**Issue by peterbsmyth** [bod-project/bod-api#2]
#### Scenario

Given: 
When: 
Then: 

#### Acceptance Criteria
-

**Comment by tmonks** [comment]
All set to review on Heroku. To also retrieve Exercise data long with Session Items, put this in the query body: `{ "include": [ { "relation": "exercise" } ] }`

**Comment by peterbsmyth** [comment]
2:00
