### ISSUE TITLE
Users - Authentication - I should be able to Create a User Account from a Google OAuth Login

### ISSUE THREAD

**Issue by peterbsmyth** [bod-project/bod-api#8]
#### Background
This application is going to link to an athlete's YouTube account. How far we can integrate will be in the hands of YouTube. The starting point is being able to create a body-factory user account by linking to a google OAuth login.

#### Scenario
Given: 
When: 
Then: 

#### Acceptance Criteria
-

**Comment by tmonks** [comment]
I've done some initial research this week on how to implement Google OAuth login with Loopback, and it sounds like using the [Passport adapter](https://loopback.io/doc/en/lb4/Authentication-passport.html) is the way to go. Here is my game plan for working out how to set it up. Please let me know if you have any questions, concerns or suggestions @peterbsmith2. 

- review [how Passport works and key concepts](http://www.passportjs.org/docs/downloads/html/)
- complete the recommended starting point tutorial - [JWT todo example tutorial](https://loopback.io/doc/en/lb4/Authentication-tutorial.html)
- review the instructions on how to implement [Passport Adapter for Authentication](https://loopback.io/doc/en/lb4/Authentication-passport.html)
- try the [example-passport-login](https://github.com/strongloop/loopback-next/tree/master/examples/passport-login) project (got this working successfully already, but will need to revisit)
- complete [YouTube API Project With Authentication](https://www.youtube.com/watch?v=r-yxNNO1EI8) to learn about authenticating and interacting with the Youtube API
